obinslab/obinslab-starter-translations

locales/es.yml, locales/locales.json
modified locales.json adding spanish and created es.yml with translation from en.ylm.
=> Spanish translation

locales/locales.json, locales/vi.yml
Hope I won't do anything wrong
=> Vietnamese translation for Obinslab Starter

locales/locales.json, locales/ms.yml
I'm not the most proficient at the language but the translations should be understandable at most
=> Add Malay Translation

locales/fr.yml, locales/locales.json
Update locales.json to add french and translate en.yml to french.
=> French translation

README-de.md, README-es.md, README.md, locales/de.yml, locales/locales.json
This PR adds german (`de`) translations.
- Added `de.yml`
- Added translation to `locales.json`
- Fixed missing commas in `locales.json`
- Added german README
Prost! 🍻
=> Add German translations

locales/en.yml, locales/locales.json, locales/nl.yml
Fixed the English translations, added some Dutch translations (WIP).
I will continue translating the English strings to Dutch tomorrow, and see if I have made any grammar errors :).
But for the English part, I fixed some translations.
=> Fixed the English translations, added some Dutch translations (WIP)

locales/fr.yml
minor fix + updated fr translation for 1.0.11 Obinslab starter version
=> Update fr.yml for 1.0.11 Obinslab starter version

locales/locales.json, locales/pl.yml
Hi 
I just finished Polish translation for Starter app. As Anne Pro is getting more presence in Poland I think it might be usefull. 
I didn't translate "Game Wheel" button name. I don't know what is the function of it so I didn't wanted to mess it up and word for word translation does not make much sense in Polish. 
If you have any questions or suggestion just let me know. 
Best regards 
Paweł
=> Polish translation

locales/id.yml, locales/locales.json
Hey, i'm Anne Pro 2 user since the launch as well as native Indonesia. Hope this can help your translation project :)
=> Adding Bahasa Indonesia locale

locales/hu.yml, locales/locales.json
I've translated all the exposed strings to Hungarian, I know about multiple people who have bought one of these and don't speak English.
Some are loosely translated, I had to be creative. Unfortunately we have no proper word or term for those.
=> Hungarian translation

locales/vi.yml
- Added new translations
- Changed some terms from previous versions to make the translation more understandable
=> Vietnamese update

locales/hu.yml
One of my testers have suggested to correct some translations and I've fixed some grammar issues.
=> Minor corrections and grammar

.vscode/settings.json, README-de.md, README-es.md, README-fr.md, README-it.md, README-ru.md, README-th.md, README-zh_CN.md, locales/it.yml, locales/locales.json
Also, the README should be updated to match the new name of the program, `ObinsKit`
=> Added italian translation

README-ja.md, README.md, locales/ja.yml, locales/locales.json
Hi,
Translated v1.1.4.
I would be happy to merge this change for my Japanese friends.
=> Japanese (ObinsKit v1.1.4)

locales/no.yml
Norwegian (bokmål) locale added
=> Add Norwegian language locale

locales/da.yml, locales/locales.json
As a native Danish speaker, I've tried translating everything to the best of my abilities. For the majority of the translations they should be accurate, however some words or sentences may be a bit "off", as they don't have any direct translations.
=> Add Danish translations

locales/ru.yml
Lines 35-37 need checking in a real application (don't have my Anne yet 😪)
Was:
```
common.return: Return
common.refresh: Refresh
common.date: Date
```
I've translated the left ones in the translation file, should be all set for Russian.
Still needs full testing in the app.
=> Fulfill Russian translation

locales/pt-PT.yml
Added Portuguese language support to ObinsLab Starter/ObinsKit.
I don't have an ANNE PRO 2 or 1 but just wanted to help.
=> Added the Portuguese Language

locales/ar.yml, locales/locales.json
Hey guys
hope you're having a good day, 
I just finished translating the application into an Arabic language, because I though it may be useful for anyone that doesn't have a good background in English. 
I tried to translate everything as possible, but there's some sentences I didn't translate because either they don't have a specific translation in Arabic or they are known as there English terms.
if there is any issue or error please let me know.
=> Arabic translation 

locales/pl.yml
I fixed some weirdnesses and added translations for ones that were not translated yet
=> Some changes in polish language

locales/cs.yml, locales/locales.json
=> Czech translations

locales/pt-BR.yml
I added and/or improved the translation from English to Brazilian Portuguese.
Some terms were not translated.
=> Improved pt-BR translation.

locales/pt-BR.yml
Hello,
I noticed that new terms were inserted and there was a typo in two other terms.
I performed the translation and necessary adjustments.
Kind regards.
=> I performed the translation remove typos.
